spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tpdb}
    username: ${SPRING_DATASOURCE_USERNAME:tpuser}
    password: ${SPRING_DATASOURCE_PASSWORD:tppass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
